Génère des tuiles vectorielles pour la carte du tableau de bord
BaseAdresseNationale/mes-adresses-api pull request #309
Opened 2022-02-01 11:04 UTC by cedric-famibelle-pronzola

2022-02-12 09:25 UTC, jdesboeufs requested changes

2022-02-12 09:25 UTC, jdesboeufs commented on package.json
> +    "zlib": "^1.0.5"
zlib est un module natif Node.js.
Inutile de le mettre ici.

2022-02-12 09:25 UTC, jdesboeufs commented on lib/util/serve-tiles.js
> +    const tileIndex = geojsonVt(featureCollection, {maxZoom: z, indexMaxZoom: z})
Cette étape est coûteuse et devrait être incluse dans le useCache. Donc il faut revoir la fonction dans le `useCache`, et ce helper.
Il faut déterminer un maxZoom pertinent.
On peut cacher le résultat de computeStats et le tileIndex.

2022-02-12 09:25 UTC, jdesboeufs commented on lib/util/serve-tiles.js
> +    const tileIndex = geojsonVt(featureCollection, {maxZoom: z, indexMaxZoom: z})
Pour satisfaire ta curiosité, sur `ban-plateforme` c'est différent car on charge déjà les données qu'on veut utiliser dans la tuile. Le coût n'a rien à voir.

2022-02-12 09:25 UTC, jdesboeufs commented on lib/routes/stats.js
> +app.route('/tiles/:z/:x/:y.pbf')
Revoir le nom de l'URL.
Par exemple `/couverture-tiles/:z/:x/:y/pbf`

2022-02-16 13:44 UTC, jdesboeufs requested changes

2022-02-16 13:44 UTC, jdesboeufs commented on lib/routes/stats.js
> +    const pbf = tile ? vtpbf.fromGeojsonVt({communes: tile}) : ''
Si pas de tuile il faut retourner No Content (204) ou 404 si hors périmètre.

2022-02-16 13:48 UTC, jdesboeufs approved these changes

2022-02-16 13:50 UTC, jdesboeufs commented
Attendre la finalisation du chantier front associé avant de merger.

2022-03-02 14:35 UTC, tmerlier approved these changes

2022-03-02 14:36 UTC, tmerlier commented
> Attendre la finalisation du chantier front associé avant de merger.

Le front est prêt https://github.com/BaseAdresseNationale/mes-adresses/pull/503

2022-03-02 16:52 UTC, merged