Amélioration de la modification/suppression en masse des numéros
BaseAdresseNationale/mes-adresses-api pull request #315
Opened 2022-03-07 14:21 UTC by cedric-famibelle-pronzola

## ⚠️ Liée à la [PR mes-adresses #509](https://github.com/BaseAdresseNationale/mes-adresses/pull/509)

- Création d'un nouveau schéma spécifique à la modification en masse
- Amélioration de la méthode `batchUpdateNumeros`
- Création de la méthode `batchRemoveNumeros`
- Ajout de la méthode `DELETE` à la route `/bases-locales/:baseLocaleId/numeros/batch`

2022-03-18 10:23 UTC, jdesboeufs requested changes

2022-03-18 10:23 UTC, jdesboeufs commented on lib/models/numero.js
> +    _id: {$in: numeros}
Tu dois aussi ajouter le critère `_bal` sinon tu peux supprimer les données de qui tu veux.

2022-03-18 10:23 UTC, jdesboeufs commented on lib/models/numero.js
> +    if (Object.hasOwnProperty.call($set, key)) {
Déprécié et trop compliqué.
D'ailleurs on ne comprend pas ce que tu veux faire ici.

2022-03-18 10:23 UTC, jdesboeufs commented on lib/models/numero.js
> +  positionType: Joi.string().valid(
Doit être optionnel

2022-03-18 10:23 UTC, jdesboeufs commented on lib/models/numero.js
> +  voie: Joi.string().custom(validObjectID),
Doit être optionnel

2022-03-18 10:23 UTC, jdesboeufs commented on lib/models/numero.js
> +  certifie: Joi.boolean()
Doit être optionnel

2022-03-18 10:23 UTC, jdesboeufs commented on lib/models/numero.js
> +    _id: mongo.parseObjectID(voie)
_bal manquant

2022-03-18 10:23 UTC, jdesboeufs commented on lib/models/numero.js
> +    throw new Error('Voie not found')
On a pas `http-errors` sur ce dépôt ?

2022-03-18 10:23 UTC, jdesboeufs commented on lib/models/numero.js
> +      _id: mongo.parseObjectID(toponyme)
_bal

2022-03-18 10:23 UTC, jdesboeufs commented on lib/models/numero.js
> +  const orExpression = [
Il faut documenter/commenter cette partie on ne comprend pas bien.

2022-04-11 08:17 UTC, jdesboeufs commented
Je reprends ce sujet, désolé.

2022-04-25 15:12 UTC, jdesboeufs approved these changes

2022-04-26 13:50 UTC, tmerlier approved these changes

2022-04-26 13:51 UTC, merged