Validation des schémas de données grâce au validateur-bal
BaseAdresseNationale/mes-adresses-api pull request #336
Opened 2022-06-15 17:23 UTC by tmerlier

## Contexte
Actuellement la validation des modèles est effectuée avec [joi](https://joi.dev). 
Cependant, la majorité des vérifications consiste à imiter le travaille que fait le [validateur-bal](https://github.com/BaseAdresseNationale/validateur-bal) afin que les BAL soient conformes au format.

Des différences de validation ont fini par voir le jour entre Mes Adresses et le Validateur, empêchant la publication de certaines BAL (ex : voie de moins de 3 caractères).

## Évolution
Cette PR propose de remplacer le `Joi` par une validation faite maison aidée par le `validateur-bal`. 

Les modèles de données seront donc toujours en accord avec la dernière version du `validateur-bal`. Et les messages d'erreur étant aussi ceux du validateur-bal, ils peuvent être directement renvoyés à l'utilisateur.

De plus, ne plus dépendre de `Joi` permet d'effectuer des validations asynchrones personnalisées avec des messages d'erreur en français. `Joi` s'est avéré ne pas être très adapté à ce besoin.

-----------------

## Nouveau système de validation de schéma
### Schémas
La validation est inspirée des schémas proposé par `Joi`. Le principe consiste à donner un objet où chaque clef est un champ à valider. À chacune de ces clefs est attachée un schéma de validation strictement formaté comme suit :

| clef         | valeur | description |
|--------------|-----|-----------|
| valid |  function |  Fonction de validation propre au champ. Elle prend en paramètre, la valeur de la clef à vérifier et un agrégateur d'erreur. Peut-être `null` si aucune validation spécifique n'est nécessaire   |
| isRequired      |  true/false |  `true` si le champ est obligatoire |
| nullAllowed      |  true/false |  `true` si le champ peut valoir `null` |
| type      |  `string`, `number`, `array`, `object` |  Permet de préciser le type de donnée attendu |

Exemple, le schéma de création d'un numéro : 
```
const createSchema = {
  numero: {valid: validNumero, isRequired: true, nullAllowed: false, type: 'number'},
  suffixe: {valid: validSuffixe, isRequired: false, nullAllowed: true, type: 'string'},
  positions: {valid: validPositions, isRequired: false, nullAllowed: false, type: 'array'},
  certifie: {valid: null, isRequired: false, nullAllowed: false, type: 'boolean'},
  …
}
```

### Validation des schémas
La validation des schémas est effectuée par la méthode `validSchema`. Celle-ci prend en paramètre le `payload` et le schéma (voir au dessus), et vérifie que le `payload` reçu respecte le schéma qui lui est imposé.

Elle s'assure tout d'abords que les pré-requis `isRequired`, `nullAllowed` et `type` du schéma sont respectés. En ensuite, si celle-ci est définie, elle appelle la fonction `valid` du schéma qui elle va s'assurer que les validations spécifiques à la clef sont respectées. C'est dans cette méthode `valid` qu'est appelé le Validateur BAL.

Tout au long du processus, un agrégateur `error` est alimenté avec les différentes erreurs qui auront été relevées.

Pour terminer, `validSchema` retourne `{value, error}`, `value` sera le `payload` qui aura été reconstitué et `error` est notre agrégateur d'erreur.

### Agrégateur d'erreur
Comportant toutes les erreurs qui auront été trouvée durant la validation du schéma, il est alimenté à l'aide la fonction helper `addError`. Elle permet d'ajouter la clef d'un champ si celle-ci n'a n'existe pas encore, mais aussi d'accumulé les erreurs sans les écraser.

Voici un exemple du contenu de l'agrégateur pour la validation d'un numéro :
```
 {
    toponyme: ['La valeur du champ toponyme est incorrecte'],
    parcelles: ['Le numéro de parcelle "KSUSH782" est invalide'],
    certifie: ['Le champ certifie doit être de type "boolean"']
  }
```
--------

## Fonctionnalité non répliquée
La fonctionnalité `Joi.default()`, permettant d'attribuer une valeur par défaut à un champ laissé à `null`, n'a pas d'équivalent dans le nouveau système de schéma.
Celle-ci n'était utilisée que pour attribuer `[]` aux parcelles d'un numéro et était de toute façon assurée par la méthode `Numero.create` qui attribue déjà des valeurs par défauts là où c'est nécessaire.

2022-07-08 08:35 UTC, jdesboeufs commented on lib/models/__tests__/base-locale.mongo.js
> -    token: 'hack'
Pourquoi cette ligne disparait-elle ?

2022-07-11 13:53 UTC, GllmR requested changes
La phrase `Le nom est trop court (1 caractère minimum)` peut porter à confusion. 

Si elle fait moins d’un caractère, on peut la considérer comme vide.

2022-07-11 13:53 UTC, GllmR commented on lib/models/position.js
> +        addError(error, 'positions', 'le champ point.coordinates est incorrecte')
`'Le champ point.coordinates est incorrect'`
ou
`'La valeur du champ point.coordinates est incorrecte'`

2022-07-11 13:53 UTC, GllmR commented on lib/models/position.js
> +      addError(error, 'positions', 'le champ point.coordinates est incorrecte')
`'Le champ point.coordinates est incorrect'`
ou
`'La valeur du champ point.coordinates est incorrecte'`

2022-08-12 13:16 UTC, GllmR approved these changes

2022-08-16 08:56 UTC, Maxine-Le-Pennec approved these changes

2022-08-31 12:35 UTC, tmerlier commented on lib/models/voie.js
> +}
L'expression régulière se charge déjà de contrôler la longueur, car elle attend un premier caractère, chiffre ou lettre majuscule et ensuite trois chiffres obligatoirement, donc le `code.length !== 4` est superflu.

Je retire ça !

2022-09-01 07:38 UTC, merged