Ajout de la propriété `_deleted` en remplacement de la suppression d’une BAL
BaseAdresseNationale/mes-adresses-api pull request #337
Opened 2022-06-16 12:17 UTC by GllmR

Actuellement, lorsqu’un utilisateur supprime une Base Adresse Locale, celle-ci est supprimée définitivement.

Cette PR propose de modifier ce comportement : à la place de supprimer la BAL, nous ajoutons la propriété `_deleted`, qui contient la date de suppression de la Base Adresse Locale.
De cette façon, et après modification de la partie client, nous pourrons proposer à l’utilisateur de récupérer sa ou ses BALs supprimées.

Modifications : 
- Ajout de la propriété `_deleted: null` à la création d'une Base Adresse Locale
- Modification de la route `/bases-locales/{_id}` (ajout de la propriété `_deleted: {dateDeSuppression}` si la BAL n’est pas un BAL de démonstation)
- Ajout d’un script de migration qui ajoute la propriété `_deleted`aux BALs qui ne l’ont pas
- Mise à jour des tests

2022-06-20 10:05 UTC, tmerlier requested changes
Nous pourrions rajouter un test pour s'assurer de la suppression des BAL de démo

2022-06-20 12:30 UTC, cedric-famibelle-pronzola commented
> Après le lancement du script de migration, je n'ai pas de log m'indiquant la fin. Il est en attente (curseur clignotant). En vérifiant la base de données, il a pourtant bien fonctionné thinking

Après vérification le script est en cours (certains numéros n'ont toujours pas la propriété _deleted).
Le nombre important de numéros dans la base de données explique les délais de finalisation

2022-06-20 12:39 UTC, cedric-famibelle-pronzola approved these changes

2022-06-21 14:26 UTC, tmerlier requested changes

2022-06-21 14:26 UTC, tmerlier commented on lib/models/__tests__/base-locale.mongo.js
> +  await mongo.db.collection('voies').insertOne({_bal: _id, numero: 1})
```suggestion
  await mongo.db.collection('numeros').insertOne({_bal: _id, numero: 1})
```

2022-06-21 14:26 UTC, tmerlier commented on lib/models/base-locale.js
> +    _deleted: null
`_deleted` n'est pas utile ici.

2022-06-23 07:16 UTC, jdesboeufs commented on migrations/2022-06-15-safe-deleted.js
> +  while (await balCursor.hasNext()) {
Ce n'est pas une opération spécifique donc tu n'as pas besoin du curseur. Un simple `updateMany` suffit, et retournera le décompte.

2022-06-23 10:33 UTC, cedric-famibelle-pronzola commented on lib/models/base-locale.js
> +
Les toponymes ne sont pas gérés.
Le `new Date` devrait être un paramètre.
Comme ça, `voies`, `numeros`, `bases_locales`, `toponymes`, auront la même Date `_updated` et `_deleted`

2022-06-27 07:14 UTC, cedric-famibelle-pronzola approved these changes

2022-06-29 14:11 UTC, tmerlier requested changes

2022-06-29 14:11 UTC, tmerlier commented on cron.js
> +    every: '1h',
Une fois par jour devrait suffire je pense.

2022-06-29 14:11 UTC, tmerlier commented on lib/models/__tests__/base-locale.mongo.js
> +  t.falsy(await mongo.db.collection('bases_locale').findOne({_id}))
```suggestion
  t.falsy(await mongo.db.collection('bases_locales').findOne({_id}))
```

2022-07-04 12:58 UTC, jdesboeufs requested changes

2022-07-04 12:58 UTC, jdesboeufs commented on migrations/2022-06-15-safe-deleted.js
> +#!/usr/bin/env node
Je ne comprends pas à quoi sert cette migration ?

2022-07-04 12:58 UTC, jdesboeufs commented on lib/sync/index.js
> +async function removeSoftDeletedBALs() {
Mauvais endroit pour mettre ce code.
`sync` est un fichier qui traite exclusivement de la synchronisation avec l'API de dépôt.

2022-07-04 12:58 UTC, jdesboeufs commented on lib/sync/index.js
> +  deleteTime.setMonth(now.getMonth() - 12)
On a `date-fns` dans les dépendances je crois. Ce serait plus clair :p

2022-07-04 13:03 UTC, GllmR commented on migrations/2022-06-15-safe-deleted.js
> +#!/usr/bin/env node
Elle ajoute le champ `_deleted` à toute les BALs qui ne l'ont pas pour éviter d’avoir des soucis avec le front.

2022-07-05 08:37 UTC, cedric-famibelle-pronzola approved these changes

2022-07-05 12:46 UTC, jdesboeufs requested changes
Je stoppe la review pour le moment il y a des attributs `_deleted` sur les voies, les numéros et les toponymes et je ne pense pas que ce soit normal.

2022-07-05 12:46 UTC, jdesboeufs commented on cron.js
> +const {removeSoftDeletedBALs} = require('./lib/util/remove-soft-deleted-bals.js')
dans `lib/models/base-locale.js`

2022-07-05 12:46 UTC, jdesboeufs commented on lib/models/__tests__/base-locale.mongo.js
> +test('remove a BaseLocale', async t => {
soft delete a BaseLocale

2022-07-05 12:46 UTC, jdesboeufs commented on lib/models/base-locale.js
> +async function softDeleteContent(id) {
On avait dit qu'on ne passait le flag que sur le BAL et pas le contenu.

2022-07-05 12:46 UTC, jdesboeufs commented on lib/models/toponyme.js
> +        toponyme._deleted = t._deleted || null
Je crois que c'est impossible que `t._deleted` vale autre chose que `undefined`

2022-07-25 08:56 UTC, tmerlier requested changes

2022-07-25 08:56 UTC, tmerlier commented on lib/models/__tests__/base-locale.mongo.js
> +  t.is(numero._deleted, undefined)
Il n'est pas utile de tester ce champ s'il n'existe pas.

2022-07-25 08:56 UTC, tmerlier commented on lib/routes/__tests__/numeros.js
> +    _deleted: null
Tous les `_deleted` des tests de `Numero` doivent être retiré.

2022-07-25 08:56 UTC, tmerlier commented on lib/routes/__tests__/toponymes.js
> +    _deleted: null
Tous les `_deleted` des tests de `Toponyme` doivent être retiré.

2022-07-25 08:56 UTC, tmerlier commented on lib/routes/__tests__/voies.js
> +    _deleted: null
Tous les `_deleted` des tests de `Voie` doivent être retiré.

2022-07-25 08:56 UTC, tmerlier commented on lib/util/mongo.js
> +    }
Passer un paramètre à `decorateCreation` permettant d'ajouter ou non `_deleted` me parait plus souple et sûr que de se baser sur la présence de `token`.

2022-07-25 08:56 UTC, tmerlier commented on lib/util/remove-soft-deleted-bals.js
> +async function removeSoftDeletedBALs() {
On pourra ajouter au moins un test unitaire à cette fonction.

2022-07-25 08:56 UTC, tmerlier commented on lib/util/remove-soft-deleted-bals.js
> +async function removeSoftDeletedBALs() {
Elle ne semble pas être utilisée... non ?

2022-07-25 09:13 UTC, cedric-famibelle-pronzola requested changes

2022-07-25 09:13 UTC, cedric-famibelle-pronzola commented on migrations/2022-06-15-safe-deleted.js
> +  process.exit(1)
```suggestion
  process.exit()
```
le code `1` est utilisé en cas d'erreur

2022-07-25 09:17 UTC, cedric-famibelle-pronzola commented on lib/util/remove-soft-deleted-bals.js
> +async function removeSoftDeletedBALs() {
fonction utilisée dans `cron.js`

2022-08-10 09:12 UTC, tmerlier approved these changes

2022-08-17 14:16 UTC, tmerlier requested changes

2022-08-17 14:16 UTC, tmerlier commented on lib/routes/stats.js
> +        .filter(bal => !bal._deleted)
Pourquoi ne pas filtrer directement dans `BaseLocale.fetchByCommunes` avec une requête mongo ?

2022-08-18 13:32 UTC, tmerlier commented
Il ne faudra pas oublier de mettre la documentation de l'API à jour après le merge de cette PR.

2022-08-24 09:53 UTC, jdesboeufs requested changes

2022-08-24 09:53 UTC, jdesboeufs commented on cron.js
> +    name: 'delete soft deleted BALs',
purge old deleted BALs

2022-08-24 09:53 UTC, jdesboeufs commented on lib/util/mongo.js
> +  decorateCreation(obj, addDeleted = false) {
Pourquoi est-ce que ce n'est pas systématique ?

2022-08-24 09:53 UTC, jdesboeufs commented on lib/models/base-locale.js
> +  const deleteTime = subMonths(now, 12)
Il faudrait soit pouvoir spécifier le délai dans les paramètres, soit via une variable d'environnement, soit préciser que c'est 1 an dans le nom de la fonction. Là avec ce nom on a l'impression que ça va tous les supprimer.

2022-08-24 09:53 UTC, jdesboeufs commented on lib/models/base-locale.js
> +  })
Et les voies ? toponymes ? numéros ?
Tu peux surement extraire la liste des BAL à supprimer et les supprimer une par une, avec `cleanContent` en renfort.

2022-08-24 16:11 UTC, jdesboeufs requested changes

2022-08-24 16:11 UTC, jdesboeufs commented on lib/models/base-locale.js
> +  const softDeletedBALs = await mongo.db.collection('bases_locales').find({
Tu peux utiliser `distinct('_id', query)` plutôt que find+toArray

2022-08-24 16:11 UTC, jdesboeufs commented on lib/models/base-locale.js
> +  await Promise.all(softDeletedBALs.map(async bal => {
Un for..of séquentiel plutôt qu'une exécution en parallèle est plus adapté pour ce genre de traitement.
Sinon ça créé énormément de requêtes qui vont polluer le serveur MongoDB.

Par ailleurs il manque des `await` devant le deleteOne et le cleanContent.

2022-08-25 13:19 UTC, jdesboeufs approved these changes

2022-08-25 13:56 UTC, tmerlier approved these changes

2022-08-30 08:02 UTC, merged