Support des langues régionales (voies, toponymes)
BaseAdresseNationale/mes-adresses-api pull request #344
Opened 2022-07-12 08:31 UTC by cedric-famibelle-pronzola

Resolves #339 

Cette PR permet l'ajout de la propriété `nomAlt` aux collections `voies` et `toponymes`.

- Création du schema de validation
- Ajout de la propriété `nomAlt` aux modèles `voie` et `toponyme`
- Mise à jour des tests

Langues régionales supportées 
| Nom         | code ISO     |
|-----------|-----------|
| français | fra |
| breton   | bre |
| basque   | eus |
| alsacien   | gsw |
| corse   | cos |
| créole-guyanais   | gcr |
| créole-martiquais-guadeloupéen   | gcf |
| créole-réunionnais | rcf |
| mahorais   | swb |
| occitan | oci |

2022-07-12 09:33 UTC, tmerlier requested changes
La méthode `addNomAlt` fait défaut ici. On ne va pas ajouter les noms un à un mais bien mettre à jour tout le champ `nomAlt` en une seule fois comme on pourrait le faire aujourd'hui avec les positions par exemple.

2022-07-12 09:33 UTC, tmerlier commented on lib/nom-alt.js
> +async function addNomAlt(collectionName, id, nomAlt) {
Cette méthode n'est pas nécessaire. Tout comme pour les positions, par exemple, tout l'objet sera renvoyé et non juste une clef.

2022-07-18 09:55 UTC, tmerlier requested changes
Attention, si on fait le choix d'autoriser la valeur `null` alors, il faut l'indiquer sur chaque ligne et non directement sur le schéma `nomAlt`.

2022-07-20 13:59 UTC, tmerlier requested changes

2022-07-20 13:59 UTC, tmerlier commented on lib/models/toponyme.js
> +const {getNomAltDefault} = require('./nom-alt')
```suggestion
const nomAltSchema, {getNomAltDefault) = require('./nom-alt')
```

ou alors juste import `nomAltSchema ` et faire `nomAltSchema. getNomAltDefault `

2022-07-20 13:59 UTC, tmerlier commented on lib/models/voie.js
> +const {getNomAltDefault} = require('./nom-alt')
```suggestion
const nomAltSchema, {getNomAltDefault) = require('./nom-alt')
```

ou alors juste import `nomAltSchema ` et faire `nomAltSchema. getNomAltDefault `

2022-07-20 13:59 UTC, tmerlier commented on lib/models/nom-alt.js
> +      throw new Error(`Valeurs "nomAlt" inattendues : ${disallowedList}.\nValeurs attendues : ${allowedList}`)
Le retour chariot `/n` n'est pas nécessaire.

2022-07-21 08:42 UTC, tmerlier approved these changes

2022-07-21 09:06 UTC, jdesboeufs approved these changes

2022-07-21 13:32 UTC, GllmR approved these changes

2022-07-21 14:13 UTC, merged