Ajout des langues régionales dans l’importation / exportation au format CSV
BaseAdresseNationale/mes-adresses-api pull request #347
Opened 2022-07-20 12:38 UTC by GllmR

Cette PR propose d’ajouter la gestion des langues régionales lors de l’importation ou de l’exportation d’une Base Adresse Locale au format CSV.

- Prise en compte du champ `nomAlt` à l’exportation et importation d’une BAL en CSV
- Création d’une fonction pour créer le `header` du fichier CSV
- Utilisation de `@ban-team/shared-data/` pour vérifier les valeurs autorisées en tant que langage alternatif
- Mise à jour du validateur
- Mise à jour des tests

2022-07-20 14:09 UTC, tmerlier commented on lib/populate/extract-csv.js
> +})
Nous pourrions initialiser directement le `Set`.

```suggestion
const validAltLang = new Set(altLanguages.map(({code}) => `voie_nom_${code}`))
```

2022-07-20 14:17 UTC, tmerlier commented on lib/populate/extract-csv.js
> +}
Nous pourrions simplifier le code ici.

```suggestion
function extractValidAltKeys(row) {
  return Object.keys(row).filter(r => validAltLang.has(r))
}
```

2022-07-20 14:44 UTC, tmerlier requested changes

2022-07-20 14:44 UTC, tmerlier commented on lib/export/csv-bal.js
> +}
```suggestion
function buildHeaders(altVoiesKeys, altToponymesKeys) {
  return [
    'cle_interop',
    'uid_adresse',
    'voie_nom',
    'lieudit_complement_nom',
    'numero',
    'suffixe',
    'certification_commune',
    'commune_insee',
    'commune_nom',
    'position',
    'long',
    'lat',
    'x',
    'y',
    'cad_parcelles',
    'source',
    'date_der_maj',
    ...altVoiesKeys.map(v => `voie_nom_${v}`),
    ...altToponymesKeys.map(v => `lieudit_complement_nom_${v}`)
  ]
}
```

2022-07-20 14:44 UTC, tmerlier commented on lib/export/csv-bal.js
> +  altVoiesKeys.add(...altToponymesKeys)
Je déplacerai ces calculs juste avant l'initialisation de `header` afin qu'on puisse voir directement où ils sont utilisés.

Nous pourrions aussi simplifier, par exemple :
```
const altVoiesKeys = voies.filter(v => v.nomAlt).map((({nomAlt}) => nomAlt))
const altToponymesKeys = toponymes.filter(t => t.nomAlt).map((({nomAlt}) => nomAlt))
```

2022-07-20 14:44 UTC, tmerlier commented on lib/populate/__tests__/extract-csv.js
> +const csvFile = `cle_interop;uid_adresse;voie_nom;lieudit_complement_nom;numero;suffixe;commune_nom;position;long;lat;x;y;cad_parcelles;source;date_der_maj;voie_nom_gsw
Il n'y a pas de test pour s'assurer que les valeurs sont bien récupérées ?

2022-07-21 07:26 UTC, cedric-famibelle-pronzola reviewed
À l'export, si on choisit plusieurs langues régionales, il n'y a que la première qui apparaît.
Il y a ensuite la colonne `nom_voie_undefined`

2022-07-21 07:45 UTC, GllmR commented
> À l'export, si plusieurs langues régionales sont enregistrées, il n'y a que la première qui apparaît. Il y a ensuite la colonne `nom_voie_undefined` dans le csv téléchargé.

C'est corrigé !

2022-07-21 08:40 UTC, cedric-famibelle-pronzola requested changes

2022-07-21 08:40 UTC, cedric-famibelle-pronzola commented on lib/export/csv-bal.js
> +  }
`headers` n'est pas return

2022-07-21 09:07 UTC, tmerlier requested changes

2022-07-21 09:07 UTC, tmerlier commented on lib/populate/extract-csv.js
> +const validAltLang = new Set(altLanguages.map(({code}) => `voie_nom_${code}`))
À faire également pour les toponymes.

2022-07-21 09:10 UTC, jdesboeufs commented on lib/export/__tests__/csv-bal.js
> +    lieudit_complement_nom_gsw: 'Die Mühle',
Pourtant c'est ce que teste ce test non ?

2022-07-21 09:14 UTC, GllmR commented on lib/export/__tests__/csv-bal.js
> +    lieudit_complement_nom_gsw: 'Die Mühle',
C'est le test createRow, on envoie le nomAlt de la ligne 31 et on attend cette ligne en retour.

2022-07-21 13:03 UTC, jdesboeufs approved these changes

2022-07-21 13:22 UTC, tmerlier commented on lib/populate/extract-csv.js
> +        nomAlt: toponymeRows[0].localizedValues.voie_nom || null,
Nous sommes d'accord que le Validateur BAL gère les noms de toponymes comme des voies ?

2022-07-21 13:24 UTC, tmerlier approved these changes

2022-07-21 13:25 UTC, cedric-famibelle-pronzola approved these changes

2022-07-21 13:45 UTC, jdesboeufs commented on lib/populate/extract-csv.js
> +        nomAlt: toponymeRows[0].localizedValues.voie_nom || null,
Le validateur ne sait pas ce qu'est un toponyme, il ne comprend que des lignes, et il s'intéresse pas vraiment au numéro.

2022-07-21 14:22 UTC, merged