Amélioration des libellés des voies et des toponymes en majuscule lors de l'import
BaseAdresseNationale/mes-adresses-api pull request #354
Opened 2022-08-03 12:45 UTC by cedric-famibelle-pronzola

Resolves #353 

- Ajout de la dépendance [@etalab/adresses-util](https://github.com/BaseAdresseNationale/adresses-util)
- Création de 2 fonctions `beautifyUppercased` (pour la propriété `nom`) et `beautifyNomAlt` (pour `nomAlt`)
- Utilisation des fonctions d'amélioration dans `lib/populate/extract-csv`

2022-08-04 08:01 UTC, tmerlier requested changes

2022-08-04 08:01 UTC, tmerlier commented on lib/populate/extract-csv.js
> +        nomAlt: beautifyNomAlt(toponymeRows[0].localizedValues.voie_nom),
Attention en l'état `beautifyNomAlt` renvoi `undefined` et non `null`.
```suggestion
        nomAlt: toponymeRows[0].localizedValues.voie_nom ? beautifyNomAlt(toponymeRows[0].localizedValues.voie_nom) : null,
```

2022-08-04 08:01 UTC, tmerlier commented on lib/populate/extract-csv.js
> +        nomAlt: beautifyNomAlt(voieRows[0].localizedValues.voie_nom),
```suggestion
        nomAlt: voieRows[0].localizedValues.voie_nom ? beautifyNomAlt(voieRows[0].localizedValues.voie_nom) : null,
```

2022-08-04 14:31 UTC, tmerlier approved these changes

2022-08-10 09:23 UTC, tmerlier requested changes
Nous pourrions améliorer `adresses-util` afin de gérer ce problème de quote/apostrophe.

2022-08-24 09:38 UTC, jdesboeufs requested changes

2022-08-24 09:38 UTC, jdesboeufs commented on lib/util/string.js
> +function beautifyNomAlt(nomAlt) {
Cette fonction modifie l'objet alors que celle du dessus renvoie une nouvelle version.
Tu devrais utiliser `mapValues` de `lodash`

2022-08-24 09:38 UTC, jdesboeufs commented on lib/populate/extract-csv.js
> +    .groupBy(r => normalize(r.parsedValues.voie_nom))
Pourquoi ce changement ?
Tu es conscient que ces deux fonctions font les choses très différemment ?

2022-08-24 09:38 UTC, jdesboeufs commented on lib/populate/extract-csv.js
> +  const toponymesIndex = keyBy(toponymes, t => normalize(t.nom))
Idem

2022-08-24 09:38 UTC, jdesboeufs commented on lib/populate/extract-csv.js
> +    .groupBy(r => normalize(r.parsedValues.voie_nom))
Idem

2022-08-24 09:38 UTC, jdesboeufs commented on lib/populate/extract-csv.js
> +  const voiesIndex = keyBy(voies, v => normalize(v.nom))
Idem

2022-08-24 09:38 UTC, jdesboeufs commented on lib/populate/extract-csv.js
> +    .groupBy(r => `${r.parsedValues.numero}@@@${r.parsedValues.suffixe}@@@${normalize(r.parsedValues.voie_nom)}`)
Idem

2022-08-24 09:38 UTC, jdesboeufs commented on lib/populate/extract-csv.js
> +      const voieString = normalize(numeroRows[0].parsedValues.voie_nom)
Idem

2022-08-24 09:38 UTC, jdesboeufs commented on lib/populate/extract-csv.js
> +      const toponymeString = numeroRows[0].parsedValues.lieudit_complement_nom ? normalize(numeroRows[0].parsedValues.lieudit_complement_nom) : null
Idem

2022-08-24 09:38 UTC, jdesboeufs commented on migrations/2021-04-20-new-toponyme.js
> +  const toponymesIndex = keyBy(toponymes, t => normalize(t.nom))
Idem

2022-08-24 09:38 UTC, jdesboeufs commented on migrations/2021-04-20-new-toponyme.js
> +    const normalizedComplement = normalize(voie.complement)
Idem

2022-08-24 12:21 UTC, tmerlier commented on lib/populate/extract-csv.js
> +    .groupBy(r => normalize(r.parsedValues.voie_nom))
L'idée ici étant de simplement créer un index pour la voie, l'utilisation de `normalize` me semblait approprié.

Il permet de regrouper ensemble les éventuelles variations d'écriture d'un même nom de voie (espaces en trop, accents manquants, quote à place de l’apostrophe, etc).

Le traitement de `beautify` étant fait sur la string originale, les variations différentes variation sont lissées et on obtient un nom de voie formaté comme on l'attend.

2022-08-24 16:28 UTC, jdesboeufs requested changes

2022-08-24 16:28 UTC, jdesboeufs commented on lib/util/string.js
> +    Object.keys(nomAlt).forEach(nom => {
```suggestion
    return mapValues(nomAlt, nom => beautifyUppercased(nom))
```

2022-08-30 08:43 UTC, jdesboeufs approved these changes

2022-08-30 14:02 UTC, tmerlier approved these changes

2022-08-30 14:04 UTC, merged