Intègre la récupération des BAL "supprimées"
BaseAdresseNationale/mes-adresses-api pull request #356
Opened 2022-09-01 14:41 UTC by cedric-famibelle-pronzola

Resolves #341 

- Création de `getApiRecoveryUrl`
- Modification du template de l'e-mail de récupération des BAL
- Ajout de la route `/bases-locales/:baseLocaleId/:token/recovery` (GET)

2022-09-06 09:23 UTC, tmerlier requested changes

2022-09-06 09:50 UTC, cedric-famibelle-pronzola commented on lib/emails/util.js
> +const apiUrl = getApiUrl()
j'ai voulu faire comme pour `editorUrlPattern` 🤷‍♂️😬
je me suis dit qu'il y a peut-être une logique liée à l'utilisation des variables d'environnement 😅

2022-09-06 09:52 UTC, cedric-famibelle-pronzola commented on lib/emails/recovery-notification.js
> +    </ul><%}%>
🤔 séparer les templates par exemple ?

2022-09-21 12:24 UTC, tmerlier commented on lib/emails/util.js
> +const apiUrl = getApiUrl()
Non, même pour `editorUrlPattern` c'est sans intérêt. Sauf si une variable est partagée dans le fichier où est exportée, il n'y a aucune raison de la déclarée globalement.

2022-09-21 12:42 UTC, tmerlier approved these changes

2022-09-21 12:42 UTC, merged