Modification majeur de la route /bases-locales
BaseAdresseNationale/mes-adresses-api pull request #365
Opened 2022-10-21 14:13 UTC by tmerlier

## Contexte
La route `GET /bases-locales` renvoi la liste intégrale de toutes les bases locales disponibles en base de donnée. Le nombre de ces bases locales étant désormais assez conséquent, cet appel dure plusieurs secondes et dégrade les performances de l'API.

## Évolution
Cette PR propose de renvoyer un nombre limité de réponses en permettant la pagination et d'appliquer des filtres aux requêtes.

Le nombre de réponses est limité à 20 par défaut.

### Filtres possibles
- `nom` : Recherche textuelle dans le nom de la base locale. Ce filtre à nécessité la création d'un index sur le champ `nom` des bases locales.
- `deleted` : Valeur `0` ou `1`. Si `1` seule les bases locales supprimées sont renvoyées. Si `0` seules les bases locales non supprimées sont renvoyées.

### Réponse
```
{
      page: (Number),
      limit: (Number),
      totalPages: (Number),
      basesLocales: (Array)
}
```

2022-10-24 07:50 UTC, jdesboeufs requested changes
`offset`
`limit`
`count` ou `total`
`results`

C'est "standard"

2022-10-24 07:50 UTC, jdesboeufs commented on lib/models/__tests__/base-locale.mongo.js
> -test('Find Base Locales by commune and email', async t => {
Par quoi est remplacé ce test ?

2022-10-24 07:50 UTC, jdesboeufs commented on lib/util/mongo.js
> +    await this.db.collection('bases_locales').createIndex({nom: 'text'})
Les indexes textuels MongoDB sont peu efficaces et peu adaptés à la langue française.

2022-10-24 07:50 UTC, jdesboeufs commented on lib/routes/index.js
> +      totalPages: Math.round(count / limit) || 1,
Tu maches le travail du front mais c'est pas le rôle de l'API.
Tu rappelles juste les paramètres d'entrée si tu veux, et ensuite ça doit donner :
```
{
  offset: 0,
  limit: 20,
  total: 12000,
  results: []
}
```

2022-10-24 07:50 UTC, jdesboeufs commented on lib/routes/index.js
> -    if (!req.query.codeCommune || !req.query.userEmail) {
Je n'ai pas été vigilant par le passé mais c'est dangereux d'exposer un search basé sur l'email

2022-10-24 07:50 UTC, jdesboeufs commented on lib/routes/index.js
> +function parseQueryFilters(req, res, next) {
La construction d'une requête Mongo n'a rien à faire dans le routage, elle doit aller dans le modèle.
Du coup tu dois analyser ta requête dans le contrôleur, construire des paramètres ou des options, et construire la requête Mongo dans le modèle.

2022-10-24 07:51 UTC, jdesboeufs commented on lib/routes/index.js
> +    const {cursor, count} = await BaseLocale.fetch(req.queryFilter)
Le curseur doit rester dans le modèle. Tu passes à ta fonction `offset` et `limit` (qui deviennent skip et limit)

2022-10-25 13:39 UTC, cedric-famibelle-pronzola requested changes

2022-10-25 13:39 UTC, cedric-famibelle-pronzola commented on lib/routes/index.js
> +
Le nom de la variable prête à confusion

2022-10-25 15:55 UTC, GllmR approved these changes

2022-10-26 16:53 UTC, jdesboeufs requested changes

2022-10-26 16:53 UTC, jdesboeufs commented on lib/models/base-locale.js
> +    .find({...filters})
Tu n'as créé aucun index additionnel sur la collection MongoDB. Ça veut dire que les requêtes seront peu performantes.

2022-10-26 16:53 UTC, jdesboeufs commented on lib/models/base-locale.js
> +  const limit = query.limit ? Number.parseInt(query.limit, 10) : 20
Il faut limiter la valeur. Par exemple Math.min(Number.parseInt(query.limit, 10), 100).
Par ailleurs tu ne contrôles pas si on a pas un `NaN` (`Number.isNaN`) ou si c'est compris entre 1 et un maximum.
Il faut penser à renvoyer une erreur 400 motivée si ça sort des bornes.

2022-10-26 16:53 UTC, jdesboeufs commented on lib/models/base-locale.js
> +  const offset = query.offset ? Number.parseInt(query.offset, 10) : 0
Pareil sauf pour la borne max.

2022-10-26 16:53 UTC, jdesboeufs commented on lib/models/base-locale.js
> +  if (query.deleted) {
Pareil si en dehors des valeurs autorisées => 400

2022-10-26 16:53 UTC, jdesboeufs commented on lib/models/base-locale.js
> +  if (query.nom) {
Ici et pour les suivants tu dois vérifier que c'est une string. `typeof truc === 'string'` sinon tu injecte n'importe quoi dans la requête. On peut faire des trucs drôles avec une query string ;)

2022-12-01 14:52 UTC, jdesboeufs approved these changes

2022-12-01 14:52 UTC, jdesboeufs commented on lib/models/__tests__/base-locale.mongo.js
> +  t.true(every(basesLocales, {status: 'draft'}))
🤣
`basesLocales.every(b => b.status === 'draft')`

2022-12-01 14:54 UTC, jdesboeufs commented
Et n'oublies pas la documentation ;)

2022-12-01 16:26 UTC, merged