Nouvelle fonctionnalité de fusion de commune et de BAL
BaseAdresseNationale/mes-adresses-api pull request #370
Opened 2023-03-07 14:16 UTC by tmerlier

## Contexte
Lors de la mise à jour du COG, des communes sont amenées à fusionner. Si une ou plusieurs de ces communes utilisent Mes Adresses afin de gérer leurs BAL, alors nous préparions à la main un fichier CSV issue de la fusion des communes.

Cependant, le fichier BAL ne contient pas toutes les informations "extra" utilisé dans Mes Adresses, comme le tracé des voies ou encore les commentaires.

## Nouvelle fonctionnalité
Création d'une nouvelle méthode `BaseLocale.createBaseLocaleFromCommunesMerge` accessible via une nouvelle route admin `/merge-bases-locales`.

Cette nouvelle méthode a pour objectif de créer une BAL en fusionnant d'autres BAL déjà existante sur Mes Adresses, issue de la BAN ou encore depuis un assemblage des adresses connues de la BAN.

### Code commune
La nouvelle BAL se verra assignée, sans vérification, le code renseigné en entrée afin de permettre l'utilisation d'un nouveau code commune encore inconnu de la version actuelle du COG.

### Status
La nouvelle BAL aura `Brouillon` comme statut par défaut sauf si au moins une des BAL renseignées possède un statut "plus avancé" auquel cas, son statut sera `Prête à publier`. 
> Même si toutes les BAL fusionnées ont pour statut `Publiée`, il est préférable de laisser les différentes communes se mettre d'accord et reprendre la main sur la nouvelle publication.

### Emails
La nouvelle BAL aura pour liste d'email, la fusion de toutes les adresses emails unique renseignées dans les BAL renseignés et des adresses emails supplémentaire fournies en entrée.

----

### Résumé
- `codeCommune` -> Nouveau code INSEE.
- `nom` -> Nom de la Base Adresse Locale
- `communesDeleguees` -> Liste des codes des communes à fusionner dans la nouvelle BAL
- `basesLocales` -> Liste des identifiants des BALs à fusionner dans la nouvelle BAL
- `emails` -> Liste des adresses emails administrateur à ajouter à la nouvelle BAL en plus de ceux déjà renseigné dans les BAL à fusionner (si renseigné)

2023-03-10 11:33 UTC, nkokla commented on lib/models/__tests__/base-locale.mongo.js
> +  // On s'assure que le total de voies est correspond (21 pour Mont-Bonvillers + 2 pour la BAL de test)
```suggestion
  // On s'assure que le total de voies correspond (21 pour Mont-Bonvillers + 2 pour la BAL de test)
```

2023-03-10 11:34 UTC, nkokla commented on lib/models/__tests__/base-locale.mongo.js
> +  // On s’assure que tous les champs de la voie son conservés
```suggestion
  // On s’assure que tous les champs de la voie sont conservés
```

2023-03-10 11:35 UTC, nkokla commented on lib/models/__tests__/base-locale.mongo.js
> +  // On s'assure que les numéros on gardait leur voie originel
```suggestion
  // On s'assure que les numéros ont gardés leur voie d'origine
```

2023-03-10 11:36 UTC, nkokla commented on lib/models/__tests__/base-locale.mongo.js
> +  // On s’assure que la BAL qui a été fusionné a bien été soft deleted
```suggestion
  // On s’assure que la BAL qui a été fusionnée a bien été soft deleted
```

2023-03-10 11:45 UTC, nkokla approved these changes

2023-03-13 14:04 UTC, mmortier requested changes

2023-03-13 14:10 UTC, mmortier approved these changes

2023-03-14 06:28 UTC, tmerlier commented on lib/models/__tests__/base-locale.mongo.js
> +  // Checks if all the fields have been copied and that the code commune is the one of the destination BAL.
Les commentaires sont plus souvent en anglais, mais il y a déjà un petit mix, car nous avons gardé les termes d'adresse volontairement en français pour éviter les traductions avec des termes approximatifs.

Je passe en anglais les commentaires de cette PR et garde les termes français entre parenthèses, ça me semble être un bon compromis.

2023-03-17 17:15 UTC, MaGOs92 approved these changes
Code and tests : LGTM

2023-03-17 17:22 UTC, merged