Ajouter un script pour charger les contoures des communes
BaseAdresseNationale/mes-adresses-api pull request #385
Opened 2023-04-17 13:51 UTC by fufeck

## Context

La fonction `prepareContoursCommunes` au lancement du serveur peut prendre jusqu'a 30s, car elle charge un geojson je 6000000 de lignes.

## Fonctionnalité

Charger les contoures de communes avec le `scripts/update-contours-communes.js` qui va écrire le geosjon dans le fichier `contours-communes.json` à la racine. Peut être appelé via `yarn update-contours`

2023-04-17 15:40 UTC, tmerlier requested changes

2023-04-17 15:40 UTC, tmerlier commented on .gitignore
> +contours-communes.json
Ce n'est pas une mauvaise chose de l'avoir dans le repo quand même, je pense.

2023-04-18 05:33 UTC, fufeck commented on .gitignore
> +contours-communes.json
Le fichier fait plus de 100mo, le repo git ne l'accepte pas. Je cherche autre chose

2023-04-18 06:13 UTC, fufeck commented on .gitignore
> +contours-communes.json
J'ai essayer git lfs, mais il faut payer, du coup, j'opte pour une autre méthode

2023-04-18 06:32 UTC, fufeck commented on .gitignore
> +contours-communes.json
Du coup j'ai opter pour charger le contours-commune.json au premier lancement du serveur. Ensuite il va piocher dans le fichier

2023-04-18 07:00 UTC, tmerlier requested changes

2023-04-18 07:00 UTC, tmerlier commented on lib/util/contours-communes.js
> +  }
```suggestion
  try {
    const contoursCommunes = require('../../contours-communes.json')
  } catch {
    console.log('Fetch Contours Communes...')
    const communesFeatures = await fetchContoursCommunes()
  } finally {
    communesIndex = keyBy([...communesFeatures], f => f.properties.code)
  }
```

2023-04-18 07:00 UTC, tmerlier commented on scripts/update-contours-communes.js
> +}
On pourrait reprendre les méthodes de `lib/util/contours-communes.js` pour éviter de dupliquer le code.

2023-04-20 07:54 UTC, MaGOs92 reviewed
Tests : LGTM
Code : 2 commentaires

2023-04-20 07:54 UTC, MaGOs92 commented on scripts/update-contours-communes.js
> +createContoursCommunesJson().catch(error => {
Pourquoi ne pas gérer les erreurs avec "try catch" dans createContoursCommunesJson?

2023-04-26 09:08 UTC, tmerlier reviewed
Il ne faudra pas oublier de lancer ce script lorsque les contours des communes seront mis à jour. Une petite doc avec les différents jeux de données à suivre et leur date de mise à jour approximative serait une bonne idée.

2023-04-26 09:08 UTC, tmerlier commented on lib/util/contours-communes.js
> +  const communesFeatures = await getRemoteFeatures(process.env.URL_CONTOURS_COMMUNES)
Par sécurité, j'utilise toujours un fallback dans ce genre de cas.

`const contoursCommunesURL = process.env.URL_CONTOURS_COMMUNES || http://etalab-datasets.geo.data.gouv.fr/contours-administratifs/2023/geojson/communes-100m.geojson`

2023-04-26 11:05 UTC, fufeck commented
Création de l'issue https://github.com/BaseAdresseNationale/mes-adresses/issues/781

2023-04-26 12:07 UTC, tmerlier approved these changes

2023-04-26 12:19 UTC, merged