Fufeck feat route to get and restore deleted
BaseAdresseNationale/mes-adresses-api pull request #387
Opened 2023-05-02 11:09 UTC by fufeck

## Context

https://github.com/BaseAdresseNationale/mes-adresses/issues/772

## Fonctionnalité

- Route PUT `/:id/soft-delete` pour archiver les `toponymes` et `voies`
- Route GET `/:id/delete` pour les `toponymes` et `voies` pour récupérer les éléments archivés
- Route DELETE `/:id` pour supprimer les `toponymes` et `voies`

## Relation

Ne peut pas être réaliser avant la PR https://github.com/BaseAdresseNationale/mes-adresses-api/pull/382

2023-05-09 10:02 UTC, MaGOs92 requested changes

2023-05-09 10:09 UTC, MaGOs92 commented
Tests :
Globalement je trouve que ça fonctionne très bien mais j'ai noté un problème avec la conversion en toponyme.
- Suppression d'une voie, restauration de la voie mais sans les numéros, conversion en toponyme => 
<img width="434" alt="Capture d’écran 2023-05-09 à 12 04 59" src="https://github.com/BaseAdresseNationale/mes-adresses-api/assets/4552238/3dfaa766-da7e-4e9f-89f8-8ffc4599effc">

2023-05-15 05:43 UTC, fufeck commented on lib/models/toponyme.js
> +  const now = new Date()
Je me suis inspiré du code de base, après la maj de la bal ne représente qu'une seule ligne `await mongo.touchDocument('bases_locales', value._bal, value._updated)` je ne vois pas vraiment comment et pourquoi la factoriser ?

2023-05-15 05:45 UTC, fufeck commented on lib/models/voie.js
> +
Bien vu

2023-05-15 05:46 UTC, fufeck commented on lib/models/voie.js
> +  await softRemove(voie._id)
J'ai beaucoup hésité sur ce point, mais si tu trouve ca plus logique ca me va

2023-05-15 05:51 UTC, fufeck commented
> Tests : Globalement je trouve que ça fonctionne très bien mais j'ai noté un problème avec la conversion en toponyme.
> 
> * Suppression d'une voie, restauration de la voie mais sans les numéros, conversion en toponyme =>
> 
> <img alt="Capture d’écran 2023-05-09 à 12 04 59" width="434" src="https://user-images.githubusercontent.com/4552238/237064537-3dfaa766-da7e-4e9f-89f8-8ffc4599effc.png">

Corrigé

2023-05-16 13:16 UTC, MaGOs92 commented on lib/models/toponyme.js
> +  const now = new Date()
oui pas besoin on peut laisser comme ça

2023-05-17 10:00 UTC, fufeck commented
> Autre petit bug dans le même style : https://www.loom.com/share/5a2e2f47472349f4aa2bf15fe6702a9f
> 
> Peut être qu'on devrait désactiver la feature "convertir ma voie en toponyme" quand des numéros de cette voie sont dans la corbeille?

Ca marche très bien de mon coté, a tu bien pull avant de tester ?

2023-05-19 09:20 UTC, MaGOs92 commented
Yes ça fonctionne!

2023-05-19 09:20 UTC, MaGOs92 approved these changes
LGTM!

2023-05-24 12:50 UTC, merged