Feat: route admin fusion communes
BaseAdresseNationale/mes-adresses-api pull request #432
Opened 2024-02-28 09:31 UTC by fufeck

2024-03-05 14:45 UTC, MaGOs92 requested changes

2024-03-05 14:45 UTC, MaGOs92 commented on apps/api/src/modules/admin/admin.service.ts
> +    coodeCommune,
typo : codeCommune

2024-03-05 14:45 UTC, MaGOs92 commented on apps/api/src/modules/admin/dto/fusion_bases_locales.dto.ts
> +  @IsString()
On utilise pas ValidatorCogCommune ici ? On peut partir du principe que la MAJ du COG a été faite en amont?

2024-03-05 14:45 UTC, MaGOs92 commented on apps/api/src/modules/admin/dto/fusion_bases_locales.dto.ts
> +  coodeCommune: string;
typo

2024-03-05 14:45 UTC, MaGOs92 commented on apps/api/src/modules/admin/utils/dates.utils.ts
> +export function checkQueryDateFromTo(from: string, to: string) {
On a exactement les mêmes fonctions dans le module stats. On peut pas mutualiser ces utilitaires dans shared?

2024-03-05 14:45 UTC, MaGOs92 commented on apps/api/src/modules/admin/admin.service.ts
> +          await this.baseLocaleService.findBalMetas(codeCommune);
Je comprends pas, normalement le paramètre qu'il faut passer ici c'est balId pas codeCommune

2024-03-05 14:45 UTC, MaGOs92 commented on apps/api/src/modules/admin/admin.service.ts
> +        const baseLocale: BaseLocale = await this.baseLocaleService.findOne({
Peut être utiliser la fonction findOneOrFail pour plus de sureté

2024-03-05 14:45 UTC, MaGOs92 commented on apps/api/src/modules/base_locale/base_locale.service.ts
> +      _deleted: null,
Pourquoi ne pas récupérer aussi ce qu'il y'a dans la corbeille?

2024-03-13 08:55 UTC, fufeck commented on apps/api/src/modules/admin/dto/fusion_bases_locales.dto.ts
> +  @IsString()
Justement, j'imagine que si on a deja fait passer le COG, le ValidatorCogCommune n'acceptera plus les ancienne commune

2024-03-13 09:00 UTC, fufeck commented on apps/api/src/modules/admin/utils/dates.utils.ts
> +export function checkQueryDateFromTo(from: string, to: string) {
J'ai du faire un copier coller pas beau, on n'utilise pas le date.utils dans le monde admin

2024-03-13 09:05 UTC, fufeck commented on apps/api/src/modules/base_locale/base_locale.service.ts
> +      _deleted: null,
Pas vraiment de raison, surtout pour éviter les effets de bord mais je n'en vois pas

2024-04-04 09:14 UTC, MaGOs92 approved these changes
Tests and code LGTM

2024-04-05 13:55 UTC, merged